### ISSUE TITLE
tail n -1 yields unpredictable result and no way to grab 32 bit wine bundle

### ISSUE THREAD

**Issue by apemberton** [sormy/wine-bundler#1]
https://github.com/sormy/wine-bundler/blob/fb32696a992419ea3aebd5439cfb3e1dbd85ed98/wine-bundler#L341

**Comment by sormy** [comment]
Intention was to use the latest version if there are more than one available, let me verify

**Comment by sormy** [comment]
It works fine:

<img width="722" alt="screenshot 2018-03-26 at 23 34 55" src="https://user-images.githubusercontent.com/7675583/37945457-58272a92-314e-11e8-841a-801b851f1158.png">

Probably we could fix `-w` to use also `-a` but not sure if it is worth of it.

**Comment by sormy** [comment]
Alright, I pushed commit to fix `-h`:

```
  -w (wine)     Use specific wine version (regular expression)
                (defaults to latest stable win64 or win32)
                Latest win32: -osx$
                Latest win64: -osx64$
                Latest stable win32: ^stable-.*-osx$
                Latest stable win64: ^stable-.*-osx64$
                Specific version: '^stable-3\.0-osx$'
```

**Comment by sormy** [comment]
ok, no response, resolving
